columns:
  - Pregnancies: int
  - Glucose: int
  - BloodPressure: int
  - SkinThickness: int
  - Insulin: int
  - BMI: float
  - DiabetesPedigreeFunction: float
  - Age: int
  - Outcome: category

numerical_columns:
  - Pregnancies
  - Glucose
  - BloodPressure
  - SkinThickness
  - Insulin
  - BMI
  - DiabetesPedigreeFunction
  - Age

categorical_columns:
  - Outcome

drop_columns: []

# for data transformation
num_features:
  - Pregnancies
  - Glucose
  - BloodPressure
  - SkinThickness
  - Insulin
  - BMI
  - DiabetesPedigreeFunction
  - Age

or_columns: []

oh_columns:
  - Outcome

transform_columns: []

